## ansible-playbook -i inventory.yml debian-ubuntu_server/02-install_minimal/install_minimal.yml --ask-pass

---
- name: Instalar una lista de paquetes en Debian/Ubuntu
  hosts: k8s_servers
  become: true
  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - htop
        - bmon
        - sudo