all:
  hosts:
    FreePBX:
#      ansible_host: 192.168.10.58
      ansible_user: grs
      become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_become_pass: 134679
      static_ip: 192.168.10.110
      tasks:
        - name: Obtener información del sistema
          ansible.builtin.setup:

    Debian-Testv1:
#      ansible_host: 192.168.10.59
      ansible_user: grs
      become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_become_pass: 134679
      static_ip: 192.168.10.111
      tasks:
        - name: Obtener información del sistema
          ansible.builtin.setup:



