## ansible-playbook -i inventory.yml debian/networking/set_static_ip.yml --become
---
- name: Configurar IP est치tica en servidores Debian
  hosts: KVM-grs
  become: yes  # Ejecutar como superusuario
  vars:
    static_ip: "{{ hostvars[inventory_hostname].static_ip }}"
    gateway: "192.168.10.1"  # Cambia esto con la puerta de enlace de tu red
    dns_server: "8.8.8.8"    # Cambia esto con tu servidor DNS
  tasks:
    - name: Configurar IP est치tica usando archivo Interfaces
      template:
        src: "interfaces.j2"  # Archivo de plantilla Jinja2
        dest: "/etc/network/interfaces"
      notify:
        - aplicar configuraci칩n de red

  handlers:
    - name: aplicar configuraci칩n de red
      command: systemctl restart networking



