#
---
- name: Initialize Kubernetes master node
  hosts: master
  become: true
  tasks:

    - name: Ensure Containerd configuration file is removed
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
        enabled: true

    - name: Initialize the Kubernetes cluster
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: kubeadm_init_output

    - name: Create .kube directory for root user
      file:
        path: /root/.kube
        state: directory
        mode: '0700'

    - name: Copy Kubernetes admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0644'

    - name: Change ownership of kube config
      command:
        cmd: chown $(id -u):$(id -g) /root/.kube/config

    - name: Deploy Calico network plugin
      shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml
      args:
        executable: /bin/bash

    - name: Extract join command
      shell: |
        echo "{{ kubeadm_init_output.stdout_lines | join('\n') }}" | grep -A 2 "kubeadm join" > /tmp/kube_join_command.sh
      args:
        creates: /tmp/kube_join_command.sh
      register: join_command

    - name: Display join command for workers
      debug:
        var: join_command.stdout



- name: Join worker nodes to Kubernetes cluster
  hosts: workers
  become: true
  tasks:

    - name: Ensure Containerd configuration file is removed
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
        enabled: true

    - name: Fetch join command from master
      slurp:
        src: /tmp/kube_join_command.sh
      delegate_to: k8s-master
      register: join_command_script

    - name: Save join script locally
      copy:
        content: "{{ join_command_script['content'] | b64decode }}"
        dest: /tmp/kube_join_command.sh
        mode: '0755'

    - name: Join the cluster
      shell: bash /tmp/kube_join_command.sh
      args:
        executable: /bin/bash
