# ansible-playbook -i inventory.yml ubuntu-server/k8s/create_k8s_cluster.yml --ask-become-pass
---
- name: Initialize Kubernetes master node
  hosts: k8s-cp
  become: true
  tasks:

    - name: Ensure Containerd configuration file is removed
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
        enabled: true

    - name: Initialize the Kubernetes cluster
#      command: kubeadm init --pod-network-cidr=10.31.0.0/16
      command: kubeadm init --pod-network-cidr=10.31.0.0/16
      register: kubeadm_init_output

    - name: Create .kube directory for root user
      file:
        path: /root/.kube
        state: directory
        mode: '0700'

    - name: Copy Kubernetes admin.conf to root's kube config
      ansible.builtin.copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0644'

    - name: Extract join command
      shell: |
        echo "{{ kubeadm_init_output.stdout }}" | grep "kubeadm join" > /tmp/kube_join_command.sh
      args:
        creates: /tmp/kube_join_command.sh
      register: join_command

    - name: Restart Containerd
      service:
        name: kubelet
        state: restarted
        enabled: true

    - name: Wait for 5 seconds before proceeding
      pause:
        seconds: 50

    - name: Deploy Calico network plugin
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/calico.yaml
      args:
        executable: /bin/bash

    - name: Extract join command
      shell: |
        echo "{{ kubeadm_init_output.stdout }}" | grep "kubeadm join" > /tmp/kube_join_command.sh
      args:
        creates: /tmp/kube_join_command.sh
      register: join_command

###

- name: Join worker nodes to Kubernetes cluster
  hosts: k8s-w1:k8s-w2
  become: true
  tasks:

    - name: Ensure Containerd configuration file is removed
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
        enabled: true

    - name: Fetch join command from master
      slurp:
        src: /tmp/kube_join_command.sh
      delegate_to: k8s-cp
      register: join_command_script

    - name: Save join script locally
      copy:
        content: "{{ join_command_script['content'] | b64decode }}"
        dest: /tmp/kube_join_command.sh
        mode: '0755'

    - name: Join the cluster
      shell: bash /tmp/kube_join_command.sh
      args:
        executable: /bin/bash
