# ansible-playbook -i inventory.yml ubuntu-server/tools/k8s/install-k8s.yml --ask-become-pass

---
- name: Install Kubernetes on Ubuntu nodes
  hosts: k8s-cp:k8s-w1:k8s-w2
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Add Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Set correct permissions for Kubernetes GPG keyring
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes repository to apt sources
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        mode: '0644'

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Kubernetes binaries (kubelet, kubeadm, kubectl)
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl
      ignore_errors: yes

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Configure node IP for Kubernetes
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ static_ip }}
      notify:
        - Restart kubelet

    - name: Crear archivo de configuración para módulos containerd
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Cargar módulo overlay
      shell: modprobe overlay
      become: true

    - name: Cargar módulo br_netfilter
      shell: modprobe br_netfilter
      become: true

    - name: Crear archivo de configuración de sysctl para Kubernetes
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Recargar configuraciones sysctl
      command: sysctl --system

  handlers:
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
