---
- name: Configurar SSH para permitir autenticación por clave pública
  hosts: all
  become: yes
  tasks:
    - name: Asegurarse de que PubkeyAuthentication esté habilitado en sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        validate: '/usr/sbin/sshd -t -f %s'

    - name: Reiniciar el servicio SSH para aplicar los cambios
      service:
        name: ssh
        state: restarted
