#ansible-playbook -i inventory.yml debian/networking/set_static_ip.yml --ask-pass
---
- name: Copiar clave SSH a servidores remotos
  hosts: Debian-Server-v1
  become: true
  tasks:
    - name: Copiar la clave pública SSH al servidor remoto
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
