#ansible-playbook -i inventory.yml ubuntu-server/01-ssh/sshd_config.yml --ask-pass
---
- name: Configurar SSH para claves públicas
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Asegurarse de que PubkeyAuthentication está configurado como "yes"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Asegurarse de que AuthorizedKeysFile está configurado correctamente
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AuthorizedKeysFile'
        line: 'AuthorizedKeysFile .ssh/authorized_keys'
        state: present

    - name: Reiniciar el servicio SSH para aplicar cambios
      service:
        name: sshd
        state: restarted
