---
- name: Encender máquinas virtuales apagadas en un servidor KVM remoto
  hosts: kvm_servers
  become: yes
  tasks:
    - name: Listar todas las máquinas virtuales (activas y apagadas)
      command: virsh list --all
      register: result
      delegate_to: localhost  # Esto se ejecuta en el host que controla el servidor KVM

    - name: Filtrar las máquinas apagadas
      set_fact:
        apagadas: "{{ result.stdout_lines | select('search', 'shut off') | map('regex_replace', '^.*?([a-zA-Z0-9-_]+).*$', '\\1') | list }}"

    - name: Encender las máquinas virtuales apagadas
      virt:
        name: "{{ item }}"
        state: running
        hypervisor: "qemu+ssh://root@{{ inventory_hostname }}/system"
      loop: "{{ apagadas }}"
      when: apagadas | length > 0
      delegate_to: localhost  # Esto ejecuta el comando localmente en la máquina de control

    - name: Mostrar las máquinas virtuales apagadas que se han encendido
      debug:
        msg: "Las siguientes máquinas virtuales fueron encendidas: {{ apagadas }}"
      when: apagadas | length > 0
