# ansible-playbook -i inventory.ini kvm-start.yml
---
- name: Encender máquinas virtuales apagadas
  hosts: kvm_servers
  become: yes  # Si es necesario ejecutar como root
  gather_facts: no

  tasks:
    - name: Verificar y encender máquinas virtuales
      community.libvirt.virt:
        name: "{{ item }}"
        state: started
        register: vm_result
      loop: "{{ groups['all'] }}"
      when: vm_result.state != 'running'
