# ansible-playbook -i inventory.yml ubuntu-server/02-networking/disable-network-config.yml --ask-become-pass
---
- name: Deshabilitar configuración de red en cloud-init
  hosts: k8s_servers
  become: true

  tasks:
    - name: Crear directorio si no existe
      file:
        path: /etc/cloud/cloud.cfg.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Escribir configuración en el archivo
      copy:
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        content: |
          network: {config: disabled}
        owner: root
        group: root
        mode: '0644'

    - name: Remove the 50-cloud-init.yaml file
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
